### ISSUE TITLE
Option to move focus directly to the Tags field

### ISSUE THREAD

**Issue by lehni** [canisbos/Cloudmarks#1]
I quite often find myself not editing title and description, but simply want to tag an entry before saving it. For this it would be best if the focus was directly in the Tags field. An option to do so would be great!

**Comment by canisbos** [comment]
I dislike adding new settings, but I decided that it would be best to initially focus the tags field instead of the title field. My guess is that most people, like you, will want to edit tags more often than titles.

I've just updated Cloudmarks with this new behavior.

**Comment by lehni** [comment]
Great, thanks! I came to expect this behavior from this Pinboard extension for Chrome:

https://github.com/samclark/pinboard
